name: CI for lab1b

on:
  push:
    paths:
      - 'lab1b/**'
  pull_request:
    paths:
      - 'lab1b/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lab1b
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin  
          java-version: 17
          java-package: jdk
          check-latest: false
          server-id: github
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.GITHUB_TOKEN }}
          overwrite-settings: true
          job-status: success
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build with Maven
        run: mvn clean install
